name: Deploy Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v2

    - name: Deploy para Render
      uses: render-examples/action@v1
      with:
        apiKey: ${{ secrets.RENDER_API_KEY }}
        serviceId: ${{ secrets.RENDER_SERVICE_ID }}
