name: Deploy para Render

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Render
      uses: johnbeynon/render-deploy-action@a0588f9aca995a15d69a72cb2bfbf37c12e5b540
      with:
        api-key: ${{ secrets.API_KEY }}
        service-id: ${{ secrets.SERVICE_ID }}
        wait-for-success: true
